#./testSocksTCPDust.sh
#./testSocksTCPMeek.sh
./testSocksTCPObfs2.sh
./testSocksTCPObfs4.sh
./testSocksTCPOptimizerFirst.sh
./testSocksTCPOptimizerMinimizeDialDuration.sh
./testSocksTCPOptimizerRandom.sh
./testSocksTCPOptimizerRotate.sh
./testSocksTCPOptimizerTrack.sh
./testSocksTCPReplicant.sh
./testSocksTCPShadow.sh