#./testSocksTCPDust.sh
#./TestSocksTCPMeek.sh
./TestSocksTCPObfs2.sh
./TestSocksTCPObfs4.sh
./TestSocksTCPOptimizerFirst.sh
./TestSocksTCPOptimizerMinimizeDialDuration.sh
./TestSocksTCPOptimizerRandom.sh
./TestSocksTCPOptimizerRotate.sh
./TestSocksTCPOptimizerTrack.sh
./TestSocksTCPReplicant.sh
./TestSocksTCPShadow.sh