#!/bin/bash
./testStunUDPOptimizerFirst.sh
./testStunUDPOptimizerMinimizeDialDuration.sh
./testStunUDPOptimizerRandom.sh
./testStunUDPOptimizerRotate.sh
./testStunUDPOptimizerTrack.sh
./testStunUDPReplicant.sh
./testStunUDPShadow.sh
./testStunUDPStarbridge.sh