#!/bin/bash
./testUDPOptimizerFirst.sh
./testUDPOptimizerMinimizeDialDuration.sh
./testUDPOptimizerRandom.sh
./testUDPOptimizerRotate.sh
./testUDPOptimizerTrack.sh
./testUDPReplicant.sh
./testUDPShadow.sh
./testUDPStarbridge.sh