#./testTCPDust.sh
#./TestTCPMeek.sh
./TestTCPObfs2.sh
./TestTCPObfs4.sh
./TestTCPOptimizerFirst.sh
./TestTCPOptimizerMinimizeDialDuration.sh
./TestTCPOptimizerRandom.sh
./TestTCPOptimizerRotate.sh
./TestTCPOptimizerTrack.sh
./TestTCPReplicant.sh
./TestTCPShadow.sh