#!/bin/bash
./testSocksTCPOptimizerFirst.sh
./testSocksTCPOptimizerMinimizeDialDuration.sh
./testSocksTCPOptimizerRandom.sh
./testSocksTCPOptimizerRotate.sh
./testSocksTCPOptimizerTrack.sh
./testSocksTCPReplicant.sh
./testSocksTCPShadow.sh
./testSocksTCPStarbridge.sh
